### ISSUE TITLE
Some suggestions regarding the library 

### ISSUE THREAD

**Issue by abhi18av** [daveyarwood/alda-clj#2]
Here are my suggestions regarding the library 

1. Commands for comparing the music-notation and the lisp-notation

2. Completing the API documentation for the `alda-clj` library.

3. Explaining the roles of the `alda.core` functions and namespace.

I'll add more here when I come to think of more 👍

**Comment by daveyarwood** [comment]
I should be improving the documentation soon. This will include adding docstrings to all of the public functions, vars and namespaces, as well as adding some kind of "getting started" guide to point newcomers in the right direction.

Re: commands for comparing the music notation and lisp notation, do you mean comparing something like `piano: c` to `(part "piano") (note (pitch :c))` ? What sort of workflow are you imagining?

**Comment by daveyarwood** [comment]
I went through tonight and completed the [API documentation](https://cljdoc.org/d/io.djy/alda-clj/CURRENT/api/alda.core). Every public function now has a detailed docstring, including usage examples!

I'm always open to feedback about how to make this library (and the Alda lisp DSL in general) easier to pick up and use, so let me know any thoughts you might have as you're exploring and trying it out.

I'm going to close this issue for now, although I'm still curious to hear more about the "commands for comparing notation" idea -- perhaps that could be a separate issue?

**Comment by abhi18av** [comment]
Thanks @daveyarwood , I liked the changes in the new doc 👍 

And as for the request, let me create a separate issue for that.

**Comment by abhi18av** [comment]
By the way, would you consider moving this to the main Alda github org? 

I think it's in good shape now :)

**Comment by daveyarwood** [comment]
I'd actually prefer for alda-clj to be thought of as an "unofficial project" building on top of Alda, but outside the scope of the development of the language itself. I think that having the repo be part of the alda-lang org would present the alda.core API as a standard Lisp DSL for Alda, which is not really my intention. I'm viewing this more as a live-coding library built on top of Alda as a lower-level tool, as opposed to something that needs to be maintained by the alda-lang org team.

On a related note: I'm going to update the Alda docs soon to remove mentions of the "inline Clojure code" feature of the language which will be dropped in Alda 2.0, and instead have a prominent section somewhere about live coding, and link to this library (and in the future, hopefully others!)
