### ISSUE TITLE
Recognize the Alda version (v1 vs. v2) and warn if it's v1

### ISSUE THREAD

**Issue by daveyarwood** [daveyarwood/alda-clj#7]
I plan to update alda-clj soon to work with Alda v2, and at that point, it won't work with Alda v1 anymore.

Once that happens, it would be nice if we recognized what version is installed (e.g. by parsing `alda version` output) and printed a warning to stderr, to give the user a heads up that the library isn't going to work for them unless they upgrade to Alda v2.

We could either do this lazily the first time someone attempts to use `play!` or `parse-events!`, or eagerly as soon as the namespace is required. ~I'm tempted to say it should be the latter.~  The latter is suboptimal because the user might want to re-bind `*alda-executable*` before using the library. So we should do it the first way. And I think once we parse the version info, we should hold onto it and repeatedly warn about lack of Alda v1 support on stderr each time the `alda` function is invoked.

**Comment by UlyssesZh** [comment]
I am working to make [alda-rb](/UlyssesZh/alda-rb) suitable to fit with both Alda 1 and Alda 2. There will be an `Alda.generation` variable that can be set as `"1"` or `"2"` (`"2"` by default) that can effect its behavior. Indeed there are some written scores that are only playable with Alda 1.

**Comment by daveyarwood** [comment]
I never got around to doing this, and in practice, it has been a non-issue, so closing this.
